// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMtxFbpLIsnnPT5Qv_ssXXoK-1Fzmfi_E',
    appId: '1:676994177431:web:355a3d3f5cd1082dc74cd2',
    messagingSenderId: '676994177431',
    projectId: 'renasya-prefb',
    authDomain: 'renasya-prefb.firebaseapp.com',
    storageBucket: 'renasya-prefb.appspot.com',
    measurementId: 'G-RN7YZZY8JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRxL-sy39Hmt3LhVcxZb0an59BZk_Bdi4',
    appId: '1:676994177431:android:973ce980e8669070c74cd2',
    messagingSenderId: '676994177431',
    projectId: 'renasya-prefb',
    storageBucket: 'renasya-prefb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYoyYZyPiO8Tnd7rj05yQT9srEatgjEno',
    appId: '1:676994177431:ios:06f1632e37537825c74cd2',
    messagingSenderId: '676994177431',
    projectId: 'renasya-prefb',
    storageBucket: 'renasya-prefb.appspot.com',
    iosBundleId: 'com.example.renasyaPrefb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYoyYZyPiO8Tnd7rj05yQT9srEatgjEno',
    appId: '1:676994177431:ios:0ab66dba963ca6b2c74cd2',
    messagingSenderId: '676994177431',
    projectId: 'renasya-prefb',
    storageBucket: 'renasya-prefb.appspot.com',
    iosBundleId: 'com.example.renasyaPrefb.RunnerTests',
  );
}
